---
- name: Configure Azure Function
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
  tasks:
    - name: Ensure Azure Function is Always On
      azure_rm_webapp:
        resource_group: senactfresourcegroup
        name: senaclabazurefunction
        plan: azure-functions-senaclab-service-plan
        state: present
        always_on: true
        frameworks:
          - name: "python"
            version: "3.10"
